apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-arief
  namespace: cert-manager
spec:
  acme:
    server: https://acme-arief-v02.api.letsencrypt.org/directory
    email: arief.kharisma@gmail.com
    privateKeySecretRef:
      name: letsencrypt-arief
    solvers:
    - http01:
        ingress:
            class: nginx
