apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: devops@kuelap.io
    privateKeySecretRef:
      name: letsencrypt-http01
    solvers:
    - http01:
        ingress:
            class: nginx
