apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: devops@kuelap.io
    privateKeySecretRef:
      name: letsencrypt-dns01
    solvers:
    - dns01:
        clouddns:
          # The ID of the GCP project
          project: kuelap-management
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-dnsmanager
            key: sa-dnsautomation-management.json
